/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;

/**
 *
 * @author User
 */
public class HomeAdmin extends javax.swing.JFrame {

    int xMouse, yMouse;
    /**
     * Creates new form main
     */
    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_Background = new javax.swing.JPanel();
        p_title1 = new javax.swing.JPanel();
        l_title1 = new javax.swing.JLabel();
        p_title2 = new javax.swing.JPanel();
        l_title2 = new javax.swing.JLabel();
        p_opt1 = new javax.swing.JPanel();
        l_opt1 = new javax.swing.JLabel();
        p_opt2 = new javax.swing.JPanel();
        l_opt2 = new javax.swing.JLabel();
        p_opt3 = new javax.swing.JPanel();
        l_opt3 = new javax.swing.JLabel();
        p_close = new javax.swing.JPanel();
        l_close = new javax.swing.JLabel();
        l_circleuprig = new javax.swing.JLabel();
        P_superiorbar = new javax.swing.JPanel();
        P_exit = new javax.swing.JPanel();
        l_exit = new javax.swing.JLabel();
        P_cuad = new javax.swing.JPanel();
        l_cuad = new javax.swing.JLabel();
        p_min = new javax.swing.JPanel();
        l_min = new javax.swing.JLabel();
        l_circlebotrig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(850, 500));
        setMinimumSize(new java.awt.Dimension(850, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 500));
        setResizable(false);

        p_Background.setBackground(new java.awt.Color(255, 255, 255));
        p_Background.setMaximumSize(new java.awt.Dimension(850, 500));
        p_Background.setMinimumSize(new java.awt.Dimension(850, 500));
        p_Background.setPreferredSize(new java.awt.Dimension(850, 500));
        p_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_title1.setBackground(new java.awt.Color(255, 255, 255));

        l_title1.setBackground(new java.awt.Color(255, 255, 255));
        l_title1.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        l_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_title1.setText("Parquee aqui: ");
        l_title1.setPreferredSize(new java.awt.Dimension(300, 57));

        javax.swing.GroupLayout p_title1Layout = new javax.swing.GroupLayout(p_title1);
        p_title1.setLayout(p_title1Layout);
        p_title1Layout.setHorizontalGroup(
            p_title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_title1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_title1Layout.setVerticalGroup(
            p_title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_title1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_Background.add(p_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 40, 300, 50));

        p_title2.setBackground(new java.awt.Color(255, 255, 255));

        l_title2.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        l_title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_title2.setText("Administracion");
        l_title2.setMaximumSize(new java.awt.Dimension(325, 57));
        l_title2.setMinimumSize(new java.awt.Dimension(325, 57));
        l_title2.setPreferredSize(new java.awt.Dimension(325, 57));

        javax.swing.GroupLayout p_title2Layout = new javax.swing.GroupLayout(p_title2);
        p_title2.setLayout(p_title2Layout);
        p_title2Layout.setHorizontalGroup(
            p_title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_title2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_title2Layout.setVerticalGroup(
            p_title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_title2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_Background.add(p_title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 100, 325, 40));

        p_opt1.setBackground(new java.awt.Color(255, 255, 255));
        p_opt1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));

        l_opt1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        l_opt1.setText("Gestion Parqueaderos");
        l_opt1.setMaximumSize(new java.awt.Dimension(240, 30));
        l_opt1.setMinimumSize(new java.awt.Dimension(240, 30));
        l_opt1.setPreferredSize(new java.awt.Dimension(240, 30));
        l_opt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_opt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_opt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_opt1Layout = new javax.swing.GroupLayout(p_opt1);
        p_opt1.setLayout(p_opt1Layout);
        p_opt1Layout.setHorizontalGroup(
            p_opt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_opt1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(l_opt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        p_opt1Layout.setVerticalGroup(
            p_opt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_opt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_opt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        p_Background.add(p_opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 300, 50));

        p_opt2.setBackground(new java.awt.Color(255, 255, 255));
        p_opt2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));

        l_opt2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        l_opt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_opt2.setText("Asignacion vigilante");
        l_opt2.setMaximumSize(new java.awt.Dimension(240, 30));
        l_opt2.setMinimumSize(new java.awt.Dimension(240, 30));
        l_opt2.setPreferredSize(new java.awt.Dimension(240, 30));
        l_opt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_opt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_opt2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_opt2Layout = new javax.swing.GroupLayout(p_opt2);
        p_opt2.setLayout(p_opt2Layout);
        p_opt2Layout.setHorizontalGroup(
            p_opt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_opt2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(l_opt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        p_opt2Layout.setVerticalGroup(
            p_opt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_opt2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(l_opt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        p_Background.add(p_opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 300, 50));

        p_opt3.setBackground(new java.awt.Color(255, 255, 255));
        p_opt3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));

        l_opt3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        l_opt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_opt3.setText("Gestion Contratos");
        l_opt3.setMaximumSize(new java.awt.Dimension(240, 30));
        l_opt3.setMinimumSize(new java.awt.Dimension(240, 30));
        l_opt3.setPreferredSize(new java.awt.Dimension(240, 30));
        l_opt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_opt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_opt3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_opt3Layout = new javax.swing.GroupLayout(p_opt3);
        p_opt3.setLayout(p_opt3Layout);
        p_opt3Layout.setHorizontalGroup(
            p_opt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_opt3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(l_opt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        p_opt3Layout.setVerticalGroup(
            p_opt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_opt3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_opt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        p_Background.add(p_opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 300, 50));

        p_close.setBackground(new java.awt.Color(255, 255, 255));
        p_close.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));

        l_close.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        l_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_close.setText("Cerrar sesion");
        l_close.setMaximumSize(new java.awt.Dimension(240, 30));
        l_close.setMinimumSize(new java.awt.Dimension(240, 30));
        l_close.setPreferredSize(new java.awt.Dimension(240, 30));
        l_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_closeLayout = new javax.swing.GroupLayout(p_close);
        p_close.setLayout(p_closeLayout);
        p_closeLayout.setHorizontalGroup(
            p_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_closeLayout.createSequentialGroup()
                .addComponent(l_close, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p_closeLayout.setVerticalGroup(
            p_closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_closeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(l_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        p_Background.add(p_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, 50));

        l_circleuprig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main.png"))); // NOI18N
        p_Background.add(l_circleuprig, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 370, 590));

        P_superiorbar.setBackground(new java.awt.Color(255, 255, 255));
        P_superiorbar.setPreferredSize(new java.awt.Dimension(850, 30));
        P_superiorbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P_superiorbarMouseDragged(evt);
            }
        });
        P_superiorbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P_superiorbarMousePressed(evt);
            }
        });
        P_superiorbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_exit.setBackground(new java.awt.Color(255, 255, 255));
        P_exit.setMaximumSize(new java.awt.Dimension(30, 30));
        P_exit.setMinimumSize(new java.awt.Dimension(30, 30));
        P_exit.setPreferredSize(new java.awt.Dimension(30, 30));

        l_exit.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        l_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_exit.setText("X");
        l_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_exit.setMaximumSize(new java.awt.Dimension(30, 30));
        l_exit.setMinimumSize(new java.awt.Dimension(30, 30));
        l_exit.setPreferredSize(new java.awt.Dimension(30, 30));
        l_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout P_exitLayout = new javax.swing.GroupLayout(P_exit);
        P_exit.setLayout(P_exitLayout);
        P_exitLayout.setHorizontalGroup(
            P_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_exitLayout.createSequentialGroup()
                .addComponent(l_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_exitLayout.setVerticalGroup(
            P_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P_superiorbar.add(P_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        P_cuad.setBackground(new java.awt.Color(255, 255, 255));
        P_cuad.setMaximumSize(new java.awt.Dimension(30, 30));
        P_cuad.setMinimumSize(new java.awt.Dimension(30, 30));
        P_cuad.setPreferredSize(new java.awt.Dimension(30, 30));

        l_cuad.setBackground(new java.awt.Color(255, 255, 255));
        l_cuad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_cuad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_cuad.setMaximumSize(new java.awt.Dimension(11, 22));
        l_cuad.setMinimumSize(new java.awt.Dimension(11, 22));
        l_cuad.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout P_cuadLayout = new javax.swing.GroupLayout(P_cuad);
        P_cuad.setLayout(P_cuadLayout);
        P_cuadLayout.setHorizontalGroup(
            P_cuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_cuadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        P_cuadLayout.setVerticalGroup(
            P_cuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_cuadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P_superiorbar.add(P_cuad, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        p_min.setBackground(new java.awt.Color(255, 255, 255));
        p_min.setMaximumSize(new java.awt.Dimension(30, 30));
        p_min.setMinimumSize(new java.awt.Dimension(30, 30));

        l_min.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        l_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_min.setText("-");
        l_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_min.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout p_minLayout = new javax.swing.GroupLayout(p_min);
        p_min.setLayout(p_minLayout);
        p_minLayout.setHorizontalGroup(
            p_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_minLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_minLayout.setVerticalGroup(
            p_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_minLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P_superiorbar.add(p_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        p_Background.add(P_superiorbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        l_circlebotrig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main_botomright.png"))); // NOI18N
        p_Background.add(l_circlebotrig, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_l_exitMouseClicked

    private void l_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseEntered
        P_exit.setBackground(Color.RED);
    }//GEN-LAST:event_l_exitMouseEntered

    private void l_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseExited
        P_exit.setBackground(Color.white);
    }//GEN-LAST:event_l_exitMouseExited

    private void P_superiorbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_superiorbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_P_superiorbarMouseDragged

    private void P_superiorbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_superiorbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_P_superiorbarMousePressed

    private void l_opt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_opt1MouseEntered
        p_opt1.setBackground(new Color(255, 222, 89));
    }//GEN-LAST:event_l_opt1MouseEntered

    private void l_opt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_opt1MouseExited
        p_opt1.setBackground(Color.WHITE);
    }//GEN-LAST:event_l_opt1MouseExited

    private void l_opt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_opt2MouseEntered
        p_opt2.setBackground(new Color(255, 222, 89));
    }//GEN-LAST:event_l_opt2MouseEntered

    private void l_opt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_opt2MouseExited
        p_opt2.setBackground(Color.WHITE);
    }//GEN-LAST:event_l_opt2MouseExited

    private void l_opt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_opt3MouseEntered
        p_opt3.setBackground(new Color(255, 222, 89));
    }//GEN-LAST:event_l_opt3MouseEntered

    private void l_opt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_opt3MouseExited
        p_opt3.setBackground(Color.WHITE);
    }//GEN-LAST:event_l_opt3MouseExited

    private void l_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_closeMouseEntered
        p_close.setBackground(new Color(255, 222, 89));
    }//GEN-LAST:event_l_closeMouseEntered

    private void l_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_closeMouseExited
        p_close.setBackground(Color.WHITE);
    }//GEN-LAST:event_l_closeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_cuad;
    private javax.swing.JPanel P_exit;
    private javax.swing.JPanel P_superiorbar;
    private javax.swing.JLabel l_circlebotrig;
    private javax.swing.JLabel l_circleuprig;
    private javax.swing.JLabel l_close;
    private javax.swing.JLabel l_cuad;
    private javax.swing.JLabel l_exit;
    private javax.swing.JLabel l_min;
    private javax.swing.JLabel l_opt1;
    private javax.swing.JLabel l_opt2;
    private javax.swing.JLabel l_opt3;
    private javax.swing.JLabel l_title1;
    private javax.swing.JLabel l_title2;
    private javax.swing.JPanel p_Background;
    private javax.swing.JPanel p_close;
    private javax.swing.JPanel p_min;
    private javax.swing.JPanel p_opt1;
    private javax.swing.JPanel p_opt2;
    private javax.swing.JPanel p_opt3;
    private javax.swing.JPanel p_title1;
    private javax.swing.JPanel p_title2;
    // End of variables declaration//GEN-END:variables
}
