/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    public Login() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        p_Background = new javax.swing.JPanel();
        l_userid = new javax.swing.JLabel();
        f_userid = new javax.swing.JTextField();
        Sep_1 = new javax.swing.JSeparator();
        l_Password = new javax.swing.JLabel();
        f_password = new javax.swing.JPasswordField();
        Sep_2 = new javax.swing.JSeparator();
        b_Ingresar = new javax.swing.JPanel();
        lb_ingresar = new javax.swing.JLabel();
        l_title = new javax.swing.JLabel();
        l_image = new javax.swing.JLabel();
        P_exit = new javax.swing.JPanel();
        l_exit = new javax.swing.JLabel();
        P_cuad = new javax.swing.JPanel();
        l_cuad = new javax.swing.JLabel();
        p_min = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        P_superiorbar = new javax.swing.JPanel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        p_Background.setBackground(new java.awt.Color(255, 255, 255));
        p_Background.setForeground(new java.awt.Color(255, 255, 255));
        p_Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_userid.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        l_userid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_userid.setText("Usuario ID:");
        p_Background.add(l_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        f_userid.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        f_userid.setForeground(new java.awt.Color(204, 204, 204));
        f_userid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        f_userid.setText("ingrese la ID del usuario");
        f_userid.setBorder(null);
        f_userid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                f_useridMousePressed(evt);
            }
        });
        p_Background.add(f_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, 20));

        Sep_1.setForeground(new java.awt.Color(0, 0, 0));
        p_Background.add(Sep_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, 10));

        l_Password.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        l_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_Password.setText("Contraseña:");
        p_Background.add(l_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        f_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        f_password.setText("**********");
        f_password.setBorder(null);
        f_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                f_passwordMousePressed(evt);
            }
        });
        p_Background.add(f_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 260, 20));

        Sep_2.setForeground(new java.awt.Color(0, 0, 0));
        p_Background.add(Sep_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 10));

        b_Ingresar.setBackground(new java.awt.Color(255, 222, 89));

        lb_ingresar.setBackground(new java.awt.Color(255, 222, 89));
        lb_ingresar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lb_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ingresar.setText("Ingresar");
        lb_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_ingresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_ingresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout b_IngresarLayout = new javax.swing.GroupLayout(b_Ingresar);
        b_Ingresar.setLayout(b_IngresarLayout);
        b_IngresarLayout.setHorizontalGroup(
            b_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(b_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(b_IngresarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lb_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        b_IngresarLayout.setVerticalGroup(
            b_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(b_IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(b_IngresarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lb_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        p_Background.add(b_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        l_title.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        l_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_title.setText("Parquee aqui");
        p_Background.add(l_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 228, 48));

        l_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bkg_login.jpg"))); // NOI18N
        l_image.setText("jLabel1");
        p_Background.add(l_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 160, 300));

        P_exit.setBackground(new java.awt.Color(255, 255, 255));

        l_exit.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        l_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_exit.setText("X");
        l_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout P_exitLayout = new javax.swing.GroupLayout(P_exit);
        P_exit.setLayout(P_exitLayout);
        P_exitLayout.setHorizontalGroup(
            P_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_exitLayout.createSequentialGroup()
                .addComponent(l_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_exitLayout.setVerticalGroup(
            P_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        p_Background.add(P_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        P_cuad.setBackground(new java.awt.Color(255, 255, 255));
        P_cuad.setMaximumSize(new java.awt.Dimension(11, 22));
        P_cuad.setMinimumSize(new java.awt.Dimension(11, 22));

        l_cuad.setBackground(new java.awt.Color(255, 255, 255));
        l_cuad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_cuad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_cuad.setMaximumSize(new java.awt.Dimension(11, 22));
        l_cuad.setMinimumSize(new java.awt.Dimension(11, 22));
        l_cuad.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout P_cuadLayout = new javax.swing.GroupLayout(P_cuad);
        P_cuad.setLayout(P_cuadLayout);
        P_cuadLayout.setHorizontalGroup(
            P_cuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_cuadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        P_cuadLayout.setVerticalGroup(
            P_cuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_cuadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_Background.add(P_cuad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 30, -1));

        p_min.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout p_minLayout = new javax.swing.GroupLayout(p_min);
        p_min.setLayout(p_minLayout);
        p_minLayout.setHorizontalGroup(
            p_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_minLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_minLayout.setVerticalGroup(
            p_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_minLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_Background.add(p_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        P_superiorbar.setBackground(new java.awt.Color(255, 255, 255));
        P_superiorbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P_superiorbarMouseDragged(evt);
            }
        });
        P_superiorbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P_superiorbarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout P_superiorbarLayout = new javax.swing.GroupLayout(P_superiorbar);
        P_superiorbar.setLayout(P_superiorbarLayout);
        P_superiorbarLayout.setHorizontalGroup(
            P_superiorbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        P_superiorbarLayout.setVerticalGroup(
            P_superiorbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        p_Background.add(P_superiorbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_Background, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_superiorbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_superiorbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_P_superiorbarMousePressed

    private void P_superiorbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_superiorbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_P_superiorbarMouseDragged

    private void l_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseEntered
        P_exit.setBackground(Color.RED);
    }//GEN-LAST:event_l_exitMouseEntered

    private void l_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseExited
        P_exit.setBackground(Color.white);
    }//GEN-LAST:event_l_exitMouseExited

    private void l_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_l_exitMouseClicked

    private void lb_ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ingresarMouseEntered
        b_Ingresar.setBackground(new Color(255, 246, 132));
    }//GEN-LAST:event_lb_ingresarMouseEntered

    private void lb_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ingresarMouseExited
        b_Ingresar.setBackground(new Color(255, 222, 89));
    }//GEN-LAST:event_lb_ingresarMouseExited

    private void f_useridMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_useridMousePressed
       if (f_userid.getText().equals("ingrese la ID del usuario")){
        f_userid.setText("");
        f_userid.setForeground(Color.black);
       }
       if (String.valueOf(f_password.getPassword()).isEmpty()){
        f_password.setText("**********");
        f_password.setForeground(Color.gray);
       }
    }//GEN-LAST:event_f_useridMousePressed

    private void f_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_passwordMousePressed
        if(String.valueOf(f_password.getPassword()).equals("**********")){
            f_password.setText("");
            f_password.setForeground(Color.black);   
        }
        if(f_userid.getText().isEmpty()){
            f_userid.setText("ingrese la ID del usuario");
            f_userid.setForeground(Color.gray);
        }
    }//GEN-LAST:event_f_passwordMousePressed

    private void lb_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_ingresarMouseClicked
        if (f_userid.getText().equals("Admin")){
            if(String.valueOf(f_password.getPassword()).equals("1234")){
                HomeAdmin newframe = new HomeAdmin();

                newframe.setVisible(true);

                this.dispose();
            }
        }else{
            HomeEmpleado newframe = new HomeEmpleado();

            newframe.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_lb_ingresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_cuad;
    private javax.swing.JPanel P_exit;
    private javax.swing.JPanel P_superiorbar;
    private javax.swing.JSeparator Sep_1;
    private javax.swing.JSeparator Sep_2;
    private javax.swing.JPanel b_Ingresar;
    private javax.swing.JPasswordField f_password;
    private javax.swing.JTextField f_userid;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l_Password;
    private javax.swing.JLabel l_cuad;
    private javax.swing.JLabel l_exit;
    private javax.swing.JLabel l_image;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel l_userid;
    private javax.swing.JLabel lb_ingresar;
    private javax.swing.JPanel p_Background;
    private javax.swing.JPanel p_min;
    // End of variables declaration//GEN-END:variables

}
