/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import Negocio.elquemanejaelparqueadero;
import java.awt.Color;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author User
 */
public class Recibo extends javax.swing.JFrame {

    int xMouse, yMouse;
    private String placa;
    private elquemanejaelparqueadero manager;
    

    /**
     * Creates new form Recibo
     */
    public Recibo(String placa) {
        
        initComponents();
        manager = new elquemanejaelparqueadero();
        placaLabel.setText(placa);
        String salidastr= manager.getHoraSalida(placa);
        String entradastr = manager.getHoraEntrada(placa);
        String idpago= manager.gerIdpago(placa);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime entrada = LocalDateTime.parse(entradastr, formatter);
        LocalDateTime salida = LocalDateTime.parse(salidastr, formatter);
        Duration duracion = Duration.between(entrada, salida);
        long minutosTotales = duracion.toMinutes();
        long ValorTarifa= manager.Tarifa(placa);
        String valor= Long.toString(ValorTarifa);
        long ValorTotal= ValorTarifa * minutosTotales;
        String valorT = Long.toString(ValorTotal);
        horaEntrada.setText(entradastr);
        horaSalida.setText(salidastr);
        id_pago.setText(idpago);
        minutos_Totales.setText(Long.toString(minutosTotales) + "minutos");
        valor_tarifa.setText(valor);
        valor_total.setText(valorT);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        horaSalida = new javax.swing.JLabel();
        placaLabel = new javax.swing.JLabel();
        horaEntrada = new javax.swing.JLabel();
        id_pago = new javax.swing.JLabel();
        p_btnimp = new javax.swing.JPanel();
        l_imp = new javax.swing.JLabel();
        minutos_Totales = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        valor_tarifa = new javax.swing.JLabel();
        valor_total = new javax.swing.JLabel();
        img_format = new javax.swing.JLabel();
        img_left = new javax.swing.JLabel();
        P_superiorbar = new javax.swing.JPanel();
        P_exit = new javax.swing.JPanel();
        l_exit = new javax.swing.JLabel();
        P_cuad = new javax.swing.JPanel();
        l_cuad = new javax.swing.JLabel();
        p_min = new javax.swing.JPanel();
        l_min = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(850, 500));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(850, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horaSalida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        horaSalida.setText("jLabel1");
        jPanel1.add(horaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 150, -1));

        placaLabel.setBackground(new java.awt.Color(0, 0, 0));
        placaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        placaLabel.setText("jLabel1");
        jPanel1.add(placaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 150, -1));

        horaEntrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        horaEntrada.setText("jLabel1");
        jPanel1.add(horaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, -1));

        id_pago.setText("jLabel1");
        jPanel1.add(id_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        p_btnimp.setBackground(new java.awt.Color(255, 255, 255));
        p_btnimp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_imp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        l_imp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_imp.setText("Imprimir recibo");
        l_imp.setPreferredSize(new java.awt.Dimension(180, 40));
        l_imp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_impMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_impMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_impMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_btnimpLayout = new javax.swing.GroupLayout(p_btnimp);
        p_btnimp.setLayout(p_btnimpLayout);
        p_btnimpLayout.setHorizontalGroup(
            p_btnimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_btnimpLayout.createSequentialGroup()
                .addComponent(l_imp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p_btnimpLayout.setVerticalGroup(
            p_btnimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_btnimpLayout.createSequentialGroup()
                .addComponent(l_imp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(p_btnimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 180, 40));

        minutos_Totales.setText("jLabel1");
        jPanel1.add(minutos_Totales, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 290, 40));

        valor_tarifa.setText("jLabel1");
        jPanel1.add(valor_tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        valor_total.setText("jLabel1");
        jPanel1.add(valor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        img_format.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recibo_parq.png"))); // NOI18N
        jPanel1.add(img_format, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        img_left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow_bar.png"))); // NOI18N
        jPanel1.add(img_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 500));

        P_superiorbar.setBackground(new java.awt.Color(255, 255, 255));
        P_superiorbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P_superiorbarMouseDragged(evt);
            }
        });
        P_superiorbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P_superiorbarMousePressed(evt);
            }
        });
        P_superiorbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P_exit.setBackground(new java.awt.Color(255, 255, 255));
        P_exit.setMaximumSize(new java.awt.Dimension(30, 30));
        P_exit.setMinimumSize(new java.awt.Dimension(30, 30));

        l_exit.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        l_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_exit.setText("X");
        l_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_exit.setMaximumSize(new java.awt.Dimension(30, 30));
        l_exit.setMinimumSize(new java.awt.Dimension(30, 30));
        l_exit.setPreferredSize(new java.awt.Dimension(30, 30));
        l_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout P_exitLayout = new javax.swing.GroupLayout(P_exit);
        P_exit.setLayout(P_exitLayout);
        P_exitLayout.setHorizontalGroup(
            P_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_exitLayout.createSequentialGroup()
                .addComponent(l_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_exitLayout.setVerticalGroup(
            P_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_exitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P_superiorbar.add(P_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        P_cuad.setBackground(new java.awt.Color(255, 255, 255));
        P_cuad.setMaximumSize(new java.awt.Dimension(30, 30));
        P_cuad.setMinimumSize(new java.awt.Dimension(30, 30));

        l_cuad.setBackground(new java.awt.Color(255, 255, 255));
        l_cuad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_cuad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_cuad.setMaximumSize(new java.awt.Dimension(11, 22));
        l_cuad.setMinimumSize(new java.awt.Dimension(11, 22));
        l_cuad.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout P_cuadLayout = new javax.swing.GroupLayout(P_cuad);
        P_cuad.setLayout(P_cuadLayout);
        P_cuadLayout.setHorizontalGroup(
            P_cuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_cuadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        P_cuadLayout.setVerticalGroup(
            P_cuadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_cuadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_cuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P_superiorbar.add(P_cuad, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        p_min.setBackground(new java.awt.Color(255, 255, 255));
        p_min.setMaximumSize(new java.awt.Dimension(30, 30));
        p_min.setMinimumSize(new java.awt.Dimension(30, 30));

        l_min.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        l_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_min.setText("-");
        l_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_min.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout p_minLayout = new javax.swing.GroupLayout(p_min);
        p_min.setLayout(p_minLayout);
        p_minLayout.setHorizontalGroup(
            p_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_minLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_minLayout.setVerticalGroup(
            p_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_minLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        P_superiorbar.add(p_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        jPanel1.add(P_superiorbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 30));

        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void l_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_l_exitMouseClicked

    private void l_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseEntered
        P_exit.setBackground(Color.RED);
    }//GEN-LAST:event_l_exitMouseEntered

    private void l_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_exitMouseExited
        P_exit.setBackground(Color.white);
    }//GEN-LAST:event_l_exitMouseExited

    private void P_superiorbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_superiorbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_P_superiorbarMouseDragged

    private void P_superiorbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_superiorbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_P_superiorbarMousePressed

    private void l_impMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_impMouseEntered
        p_btnimp.setBackground(new Color(255, 222, 89));
    }//GEN-LAST:event_l_impMouseEntered

    private void l_impMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_impMouseExited
        p_btnimp.setBackground(Color.WHITE);
    }//GEN-LAST:event_l_impMouseExited

    private void l_impMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_impMouseClicked
        HomeEmpleado newframe = new HomeEmpleado();
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_l_impMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_cuad;
    private javax.swing.JPanel P_exit;
    private javax.swing.JPanel P_superiorbar;
    private javax.swing.JLabel horaEntrada;
    private javax.swing.JLabel horaSalida;
    private javax.swing.JLabel id_pago;
    private javax.swing.JLabel img_format;
    private javax.swing.JLabel img_left;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l_cuad;
    private javax.swing.JLabel l_exit;
    private javax.swing.JLabel l_imp;
    private javax.swing.JLabel l_min;
    private javax.swing.JLabel minutos_Totales;
    private javax.swing.JPanel p_btnimp;
    private javax.swing.JPanel p_min;
    private javax.swing.JLabel placaLabel;
    private javax.swing.JLabel valor_tarifa;
    private javax.swing.JLabel valor_total;
    // End of variables declaration//GEN-END:variables
}
